// <auto-generated />
namespace SocialNetwork.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class crossconnectiontablesPostsUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crossconnectiontablesPostsUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201803161634444_cross-connection-tables-Posts-Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
